angular.
    module('basicScenario',
            ['ngRoute',
             'core',
             'login',
             'register',
             'api',
             'bookdate',
             'booklist',
             'messages',
             'user'
            ]);